remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
logo: /assets/img/logo.png
title: React Native Hardwired - Remote JSX React Native Components
description: You can now simply download React Native components from web or database sources during runtime, eliminating the need for bundle rebuilds.
show_downloads: true
