# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


defaults:
  run:
    working-directory: ./docs

permissions:
  id-token: write
  pages: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # 👇 Build steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache-dependency-path: ./docs/package-lock.json
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      # 👆 Build steps
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs/build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
